name: Twitter Bot

on:
  schedule:
    # Uruchamiaj co 1.5 godziny (co 90 minut)
    # Format: minute hour day month day-of-week
    # 0,30 oznacza: o 00:00, 01:30, 03:00, 04:30, 06:00, 07:30, 09:00, 10:30, 12:00, 13:30, 15:00, 16:30, 18:00, 19:30, 21:00, 22:30
    - cron: '0,30 * * * *'
  workflow_dispatch:  # Możliwość ręcznego uruchomienia

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    # Krok 1: Pobranie kodu z repozytorium (używamy najnowszej wersji v4)
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Krok 2: Ustawienie środowiska Python (używamy najnowszej wersji v5)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    # Krok 3: Instalacja zależności
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy requests
    
    # Krok 4: Uruchomienie bota
    - name: Run bot
      env:
        # Przekaż sekrety, mapując nazwy specyficzne dla bota na ogólne,
        # których oczekuje skrypt Pythona.
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        BOT1_ACCESS_TOKEN: ${{ secrets.BOT1_ACCESS_TOKEN }}
        BOT1_ACCESS_TOKEN_SECRET: ${{ secrets.BOT1_ACCESS_TOKEN_SECRET }}
      run: python twitter_bot.py
